#!/bin/bash
apt-get install tasksel
tasksel install lamp-server
mysql -u root -p
CREATE DATABASE wordpressdb;
CREATE USER wordpressuser@localhost IDENTIFIED BY 'wordpresspassword';
GRANT ALL PRIVILEGES ON wordpressdb.* TO wordpressuser@localhost; FLUSH PRIVILEGES;
exit
cd /tmp
wget http://wordpress.org/latest.zip
apt-get install unzip
unzip -q latest.zip -d /var/www/html/
chown -R www-data:www-data /var/www/html/wordpress
chmod -R 755 /var/www/html/wordpress
mkdir -p /var/www/html/wordpress/wp-content/uploads
chown -R www-data:www-data /var/www/html/wordpress/wp-content/uploads 
service apache2 restart
apt-get install php7.0-mysql
